name: authentication_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter
  konsole:
    path: ../konsole
  firebase_auth: ^1.1.3
  freezed_annotation: ^0.14.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  freezed: ^0.14.1+3
  mockito: ^5.0.7
  mocktail: ^0.1.2
  very_good_analysis: ^2.0.3
